name: Test Email Step

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 23f2003918@ds.study.iitm.ac.in
        run: echo "Hello, world!"
